name: EC2 Scheduler

on:
  schedule:
    - cron: "30 9 * * *" # Corrected for 3 PM IST (Stop Instance)
  workflow_dispatch:  # Allows manual trigger

jobs:
  stop-ec2:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    name: Stop EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Explicitly set region

      - name: Stop EC2 & Release EIP
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Scheduled-Solution-Arch-EC2" --query "Reservations[].Instances[].InstanceId" --output text)

          echo "Current EC2 State:"
          aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[].Instances[].State.Name"

          echo "Stopping EC2 instance: $INSTANCE_ID"
          aws ec2 stop-instances --instance-ids $INSTANCE_ID

          echo "Waiting for instance to stop..."
          aws ec2 wait instance-stopped --instance-ids $INSTANCE_ID

          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[].Instances[].PublicIpAddress" --output text)

          echo "Deleting Route 53 record..."
          aws route53 change-resource-record-sets --hosted-zone-id ZONE_ID --change-batch '
          {
            "Changes": [{
              "Action": "DELETE",
              "ResourceRecordSet": {
                "Name": "api-java.deepakvishwakarma.com",
                "Type": "A",
                "TTL": 60,
                "ResourceRecords": [{"Value": "'"$PUBLIC_IP"'"}]
              }
            }]
          }'
          
          echo "Released Public IP: $PUBLIC_IP"
